# Generated by Django 6.0.6 on 2026-06-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('diretor', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('ACAO', 'Ação'), ('COMEDIA', 'Comédia'), ('DRAMA', 'Drama'), ('FICCAO', 'Ficção Científica'), ('TERROR', 'Terror')])),
                ('assistido', models.BooleanField(default=False)),
                ('nota', models.IntegerField(blank=True, help_text='Nota pessoal de 1 a 5', null=True)),
                ('comentario_pessoal', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
